### ISSUE TITLE
Update classpath of running JVM

### ISSUE THREAD

**Issue by hanslovsky** [scijava/scyjava#10]
We may re-visit the option of updating the classpath at runtime. kivy/pyjnius#434 links [this stackoverflow post](https://stackoverflow.com/questions/45232522/how-to-set-classpath-of-a-running-jvm-in-cjni) as a possible solution for that.

**Comment by ctrueden** [comment]
Seems like a reasonable workaround to avoid the dynamic classloading woes we encountered. It wouldn't fully solve everything (e.g. if you want to dynamically load a class from a `byte[]` in memory), but in practice, would enable to effectively load additional libraries after JVM start. The brick wall would only hit us if we wanted to start doing more sophisticated things with custom class loaders—like load different versions of the same class in different class loader subtrees.

**Comment by ctrueden** [comment]
With JPype this feature is supported, so I'm going to close this issue. Here is a short demo:
```python
>>> import scyjava
>>> System = scyjava.jimport("java.lang.System")
>>> System.getProperty("java.version")
'1.8.0_332'
>>> VersionUtils = scyjava.jimport("org.scijava.util.VersionUtils")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Code/scijava/scyjava/src/scyjava/_java.py", line 362, in jimport
    return jpype.JClass(class_name)
  File "/usr/local/Caskroom/mambaforge/base/envs/scyjava-dev/lib/python3.10/site-packages/jpype/_jclass.py", line 99, in __new__
    return _jpype._getClass(jc)
TypeError: Class org.scijava.util.VersionUtils is not found

>>> scyjava.config.add_classpath(*scyjava.config.find_jars('/Users/curtis/Applications/Fiji.app'))
>>> VersionUtils = scyjava.jimport('org.scijava.util.VersionUtils')
>>> VersionUtils.getVersion(VersionUtils)
'2.89.2'
```

The only bummer is that SciJava plugin discovery does not work with dynamically added classpath elements out of the box; maybe we need to pass a `ClassLoader` or set the thread context class loader?
```python
>>> ImageJ = scyjava.jimport('net.imagej.ImageJ')
>>> ij = ImageJ()
[WARNING] Class pool is empty: forgot to call Thread#setClassLoader?
Traceback (most recent call last):
  File "ImageJ.java", line 75, in net.imagej.ImageJ.<init>
  File "Context.java", line 160, in org.scijava.Context.<init>
  File "Context.java", line 174, in org.scijava.Context.<init>
  File "Context.java", line 234, in org.scijava.Context.<init>
  File "Context.java", line 285, in org.scijava.Context.<init>
  File "ServiceHelper.java", line 168, in org.scijava.service.ServiceHelper.loadServices
  File "ServiceHelper.java", line 192, in org.scijava.service.ServiceHelper.loadService
  File "ServiceHelper.java", line 241, in org.scijava.service.ServiceHelper.loadService
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
java.lang.java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: No compatible service: org.scijava.service.SciJavaService
```

But that's not a problem at this layer of the architecture.

**Comment by ctrueden** [comment]
The only other thing we could do here in the scyjava library is make `add_endpoint` et al work somehow after the JVM has already started, by re-resolving the Maven dependency tree and then adding anything new to the classpath... but that's substantially more complex and error-prone as versions change, and would likely necessitate changes at the jgo level as well, so I'm going to deem such a feature out of scope for now.
