### ISSUE TITLE
Conversion of BigDecimal to Python fails

### ISSUE THREAD

**Issue by ctrueden** [scijava/scyjava#39]
```
>>> import scyjava
>>> BigDecimal = scyjava.jimport('java.math.BigDecimal')
>>> bd = BigDecimal("1.98734907821093790182734")
>>> bd.toString()
'1.98734907821093790182734'
>>> scyjava.to_python(bd)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.8/site-packages/scyjava/__init__.py", line 700, in to_python
    raise exc
  File ".../lib/python3.8/site-packages/scyjava/__init__.py", line 697, in to_python
    return _convert(data, py_converters)
  File ".../lib/python3.8/site-packages/scyjava/__init__.py", line 266, in _convert
    return prioritized.converter(obj)
  File ".../lib/python3.8/site-packages/scyjava/__init__.py", line 804, in <lambda>
    converter=lambda obj: float(obj.toString),
TypeError: float() argument must be a string or a number, not '_jpype._JMethod'
```

**Comment by Thrameos** [comment]
Seems like missing parathesis.  ``toString()``

**Comment by Thrameos** [comment]
Yes.  Python developers haven't really addressed my request to make str an abstraction so that Java Strings can be considered a string.  Thus working as best we can given the constraints.   Not sure why Java and Python chose to make string types concrete and mostly final, but that is what we have.
